# Generated by Django 5.1.5 on 2025-01-25 05:53

import django_rich_text_editor.rich_text_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_rich_text_editor.rich_text_editor.fields.RichTextField()),
            ],
        ),
    ]
